### ISSUE TITLE
Pulp icon font path wrong?

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/pulp2#1]
@nylnook, thanks for pointing out the leftover code on the other repo. I've cleaned this one up. I don't see the pulp icon font problem but I did fix a problem with the stylus file more generally, which could have impacted that. 

Can you pull this and do `npm run dev` to see if it is fixed for you?

**Comment by nylnook** [comment]
Hello Michael,

I just tested, and it run fine, I think it was my fault in my implementation inside docpad (I had to move files). Sorry.

But there is one little typo with the icons in pulp-icon.css:
you have 
```
.pulp-icon-dot-3:before { content: '\e809'; } /* '' */
.pulp-icon-chat:before { content: '\e809'; } /* '' */
```
so it's the same icon for both selectors...

the correct lines are : 
```
.pulp-icon-dot-3:before { content: '\e80c'; } /* '' */
.pulp-icon-chat:before { content: '\e809'; } /* '' */
```
I opened the font with Fontforge to find back the correct unicode for dot-3 ;)

**Comment by mhkeller** [comment]
Thanks! Fixed.
