### ISSUE TITLE
Recalculate img sizes for every page

### ISSUE THREAD

**Issue by tsouk** [mhkeller/pulp2#11]
Hi, I'm trying to use pages of different size, and pulp thinks that all of my pages are of the size of page-1. For example, my page-1 is slightly wider, and every other page spread ends up with a gap. I do believe the container of every <img> after that actually has the width of page-1.

Is it possible to make the container of each <img> to have the respective width?

**Comment by tsouk** [comment]
I think I found where this happens:
```
$pages.imagesLoaded().done(function () {
        var $img = $pages.find('img'),
          img_width = $img.width(),
          original_img_width = img_width,
          img_width_wrapper = img_width,
          img_height = $img.height()

        console.log($img);
        console.log('IMAGE WIDTH ---------:', img_width);

        settings.original_img_width = original_img_width

        state.setPageFormat()
        var format = state.get('format').format

        if (format == 'double') {
          img_width = img_width * 2
          img_width_wrapper = img_width + parseInt(settings.gutterWidth)
          if (init.browser[0] == 'Firefox') {
            img_width_wrapper = img_width_wrapper - 1 // Minus one for sub-pixel rendering hack
          }
          if (states.currentPage == 1) {
            $coverHoverMask.width(original_img_width)
          } else {
            $coverHoverMask.css('width', '')
          }
        }
        // Apply the dimensions from the image to the wrapper
        // Apply a bit of a margin on pages_wrapper to accommodate the gutter
        var groups = [
          {el: $pages, width: img_width},
          {el: $pagesWrapper, width: img_width_wrapper}
        ]

        _.each(groups, function (group) {
          group.el.css('max-width', (group.width) + 'px').css('max-height', img_height + 'px')
        })
```

But even though my console.logs show that Jquery is returning all the images, the width applied is always the one of the first element. Am I on the right track?

**Comment by mhkeller** [comment]
Hey @tsouk, sorry for the delay. That's definitely the function that measures things and you're correct that this doesn't work out of the box the way you're describing. It's designed to only measure the images on resize and then the page dimensions are based on that. Do you have a mockup that you could create in a separate repo (you can use dummy images instead of your art) to show what you're trying to do. I'm not sure it's possible but I can take a look. I imagine that it would be jittery measuring the new image each page turn and it might change the animation.

**Comment by tsouk** [comment]
Hi @mhkeller, I think you're right and I might have been asking for a feature that is unreasonable actually. Comic books should have the same paper size.

Eventually I want to publish a real book with the online comic. In that book, I wanted the inside flap of the cover to be illustrated, so the "flap + inside of cover (left) + first ever page" to be a panorama. In the online book I was trying to give this idea a go. I found a way around it though, you can see it here: 

http://www.ilandcomic.co.uk/chapters/0/#1

Excuse the comic book plug.
Please feel free to close this one.
Thank you!

**Comment by mhkeller** [comment]
I love this. So you've made part of the image the same as the background color. That seems like a good workaround. 

I see this has some of that gutter width issues. I'm not sure my latest fix will resolve the line when it's single pages. Let me do some more investigation

**Comment by tsouk** [comment]
hehe, cheers @mhkeller !
I'll put in some more dev work into this just before I post my new iland chapter.

**Comment by mhkeller** [comment]
Shall we close this one and continue to discuss on the gutter width issue?

**Comment by tsouk** [comment]
Yes, I'll do the honours.
