### ISSUE TITLE
Index.html in public folder throws "Error loading config. File is either missing or the JSON is malformed. Try running `config.json` it through jsonlint.com: undefined"

### ISSUE THREAD

**Issue by Corstiaan84** [mhkeller/pulp2#12]
After downloading and extracting the zip file of this repo and subsequently opening Index.html in the /public folder, the browser alerts `Error loading config. File is either missing or the JSON is malformed. Try running config.json it through jsonlint.com: undefined`.

First I validated the json from the config.json file and it is valid so thats not the issue.

Then I took a quick look at main.js to check the paths. It seems to be looking for a json file in the same directory as the js file. I tried moving the json file to /public/js but the error persisted.

Any thoughts? Thanks!

**Comment by Corstiaan84** [comment]
Never mind... Had to use `npm run dev`

**Comment by mhkeller** [comment]
Cool. Is there a spot in the docs that I should make that clearer?
