### ISSUE TITLE
How to center the page viewer in fullscreen mode

### ISSUE THREAD

**Issue by Rickkorsten** [mhkeller/pulp2#15]
How do i center the page in fullscreen mode? And is there any way to fix the screen when you hold the phone(oneplus 5 , iphone 7+) in landscape mode?

Thx

**Comment by mhkeller** [comment]
What behavior are you currently seeing in fullscreen mode? The pages should fill the screen so it would be defacto centered.

**Comment by mhkeller** [comment]
Post a screenshot of the behavior you're seeing and I'll take a look.

**Comment by mhkeller** [comment]
I'm closing some of these old issues – if you're still seeing this problem, feel free to reopen it with some more info!
