### ISSUE TITLE
index.html is missing desktop endnotes

### ISSUE THREAD

**Issue by elmimmo** [mhkeller/pulp2#16]
The HTML markup in index.html seems to be missing the markup that would make the drawer available on desktop. _Terms of services_ does have it.

**Comment by mhkeller** [comment]
@elmimmo How do you mean? Can you show a screenshot? The drawer was only supposed to be on mobile. On desktop the drawer functionality is mostly handled through the menu bar items iirc. But if you can post a screenshot of what's missing I'll take a look.

**Comment by mhkeller** [comment]
I'm going to close this to clean up issues but if you have any more info, let me know!
