### ISSUE TITLE
Shameless plug of our comic books in your README

### ISSUE THREAD

**Issue by tsouk** [mhkeller/pulp2#17]
Well, can we show off our comic books in your README please?

(...feel free to say "no" and close this btw.)

**Comment by mhkeller** [comment]
ya of course, feel free to make a PR following the same format as the others! or send the link etc.

**Comment by tsouk** [comment]
hey @mhkeller , can I have contributor access to make the PR?

**Comment by mhkeller** [comment]
You should be able to start the pull request as a normal github user. If you're just editing the readme, the easiest is to click the pencil icon at the top right of the document. It should then create a fork for you and when you've committed the changes in the browser, prompt you to submit it as a pull request.

**Comment by tsouk** [comment]
I usually go the cli way, and this is what I got:
```
$ git push origin README-ilandcomics
remote: Permission to mhkeller/pulp2.git denied to tsouk.
fatal: unable to access 'https://github.com/mhkeller/pulp2/': The requested URL returned error: 403
```

But I can try the Github web way!

**Comment by mhkeller** [comment]
If you do it on the cli you’ll need to fork the repo, push to a new branch on that repo then PR from there

**Comment by mhkeller** [comment]
Closed via https://github.com/mhkeller/pulp2/pull/18 https://github.com/mhkeller/pulp2/pull/19
