### ISSUE TITLE
Improve build system

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/pulp2#2]
I no longer like the gulp build system this uses. It's not nice that the public folder has some meaningful things in it. Instead, everything should exist in `src` and `public/` gets clobbered every time. The naming convention around `thirdparty` is also a little weird since those aren't really third party files some of the time. `modules` would be more appropriate.

**Comment by mhkeller** [comment]
This should be grouped into a larger rewrite and modernization.

**Comment by tsouk** [comment]
Yeah!
Go webpack / parcel / etc. !
