### ISSUE TITLE
New comic in the wild

### ISSUE THREAD

**Issue by elmimmo** [mhkeller/pulp2#22]
[Las finanzas de Carlota](https://multimedia.caixabank.es/lacaixa/ondemand/criteria/espacioaccionista/comicaula2020/es/sources/) is a comic books series in Spanish and Catalan using Pulp2 by Spanish bank [Caixabank](https://www.caixabank.com) as part of its education program on economics and finance for its shareholders.

You might want to add it to your [list of online comics in the wild using Pulp2](https://github.com/mhkeller/pulp2#in-the-wild).

**Comment by mhkeller** [comment]
Neat! Added to the readme.
