### ISSUE TITLE
0px gutterWidth should have absolutely no gutter

### ISSUE THREAD

**Issue by tsouk** [mhkeller/pulp2#8]
When I have double pages, designed to look like a panorama, and I have set my gutterwidth to 0px, I want there to be no double pixel edge in the middle of the two page spread.

I've found a way to do that in the whole series, but maybe we want a way of specifying "two page spreads" that don't have the edge. Or an option to turn it off.

at `/src/css/styles.styl`

```
@@ -696,7 +696,9 @@ body[data-format="double"] .page-container.viewing.right-page:after
        right 0
        position absolute
        z-index -1
-       background url('../imgs/assets/border.png') repeat-y (gutterWidth/2) top #fff
+       /* this is what makes the border between pages */
+       if gutterWidth != "0px"
+               background url('../imgs/assets/border.png') repeat-y (gutterWidth/2) top #fff
```

**Comment by mhkeller** [comment]
@tsouk This is a great idea. I just implemented your conditional in the stylesheet and added a new option to `pages.json` of `gutterBorder: false` which will disable it on a per-spread basis: https://github.com/mhkeller/pulp2/commit/52d2de1d8300d3bd27c8201440a7c6fcf3b90953

I added this to the readme and an example in the `public/data/pages.json` file

> If you want to disable the gray border between pages you can set gutterWidth to "0px" in your config.json or you can disable it on a per-spread basis by setting gutterBorder to false on the right-hand page of your spread such as in the example. This is because the gutter border is drawn as a part of the right image. You might want to add this if you want two pages to go together seamlessly.

**Comment by mhkeller** [comment]
Let me know if that works for you and I'll close.

**Comment by tsouk** [comment]
hi @mhkeller thanks for your updates! I will have a look as soon as possible as I have forked and probably need to revert and retest everything works as expected, mostly for the other changes that have come in.

**Comment by mhkeller** [comment]
Hi @tsouk, checking in if you've had a chance to test.

**Comment by tsouk** [comment]
hey @mhkeller !
Yes! sorry for forgetting to reply.
Works great. Feel free to close this one.
